/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClasesInterfacez;

import ClasesBean.Jugador;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author tcoba
 */
public class CreacionTorneos extends javax.swing.JFrame {
    Torneo torneo;
    DefaultListModel<String> modeloEquiposDuo;
    DefaultListModel<String> modeloEquiposSeleccionadosDuo;
    DefaultListModel<String> modeloEquipos;
    DefaultListModel<String> modeloEquiposSeleccionados;
    DefaultListModel<String> modeloJugadores;
    DefaultListModel<String> modeloJugadoresSeleccionados;
    
 
    
    public CreacionTorneos(Torneo torneo) {
        this.torneo = torneo;
        modeloEquipos = new DefaultListModel<>();
        modeloEquiposDuo= new DefaultListModel<>();
        modeloJugadores= new DefaultListModel<>();
        modeloEquiposSeleccionados= new DefaultListModel<>();
        modeloEquiposSeleccionadosDuo= new DefaultListModel<>();
        modeloJugadoresSeleccionados= new DefaultListModel<>();
        
        jLEquipos.setModel(modeloEquipos);
        jLEquiposDuo.setModel(modeloEquiposDuo);
        jLJugadores.setModel(modeloJugadores);
        jLEquiposSeleccionados.setModel(modeloEquiposSeleccionados);
        jLEquiposSeleccionadosDuo.setModel(modeloEquiposSeleccionadosDuo);
        jLJugadoresSeleccionados.setModel(modeloJugadoresSeleccionados);
        initComponents();
    }
    
    
    /**
     * Creates new form CreacionTorneos
     */
    public CreacionTorneos() {       
        initComponents();        
    }
  

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLJugadores = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCSeleccionTipo = new javax.swing.JComboBox<>();
        jLEquipos = new javax.swing.JList<>();
        jLJugadoresSeleccionados = new javax.swing.JList<>();
        jLEquiposSeleccionadosDuo = new javax.swing.JList<>();
        jLEquiposSeleccionados = new javax.swing.JList<>();
        jLEquipos2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jLJugadoresSeleccionados1 = new javax.swing.JList<>();
        jLEquiposDuo = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLJugadores.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 226, 130));
        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 173, 228, -1));

        jLabel1.setText("Creacion torneo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 19, -1, -1));

        jLabel2.setText("Lista registrados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 129, -1, -1));

        jCSeleccionTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Duo", "Escuadra" }));
        jCSeleccionTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSeleccionTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jCSeleccionTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 74, -1, -1));

        jLEquipos.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 226, 128));

        jLJugadoresSeleccionados.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLJugadoresSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 226, 130));

        jLEquiposSeleccionadosDuo.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLEquiposSeleccionadosDuo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 226, 128));

        jLEquiposSeleccionados.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLEquiposSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 226, 128));

        jLEquipos2.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLEquipos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 226, 128));

        jLabel3.setText("Lista seleccionados");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jBAgregar.setText(">");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jBEliminar.setText("<");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLJugadoresSeleccionados1.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLJugadoresSeleccionados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 226, 130));

        jLEquiposDuo.setModel(new javax.swing.DefaultListModel());
        jPanel1.add(jLEquiposDuo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 226, 128));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCSeleccionTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSeleccionTipoActionPerformed
        String seleccion = (String) jCSeleccionTipo.getSelectedItem();
    if("Equipos".equals(seleccion)||"Duo".equals(seleccion)){
    jLJugadores.setVisible(false);
    jLJugadoresSeleccionados.setVisible(false);
    jLEquiposDuo.setVisible(true);
    jLEquiposSeleccionadosDuo.setVisible(true);
    jLEquipos.setVisible(true);
    jLEquiposSeleccionados.setVisible(true);
    }else{
    jLJugadores.setVisible(true);
    jLJugadoresSeleccionados.setVisible(true);
    jLEquipos.setVisible(false);
    jLEquiposSeleccionados.setVisible(false);
    jLEquiposDuo.setVisible(true);
    jLEquiposSeleccionadosDuo.setVisible(true);
    }
    }//GEN-LAST:event_jCSeleccionTipoActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        String seleccion = (String) jCSeleccionTipo.getSelectedItem();
        
        if("Equipos".equals(seleccion)){
        String seleccionLista = (String) jLEquipos.getSelectedValue();
        if(seleccionLista !=null && !modeloEquipos.contains(seleccionLista)){
            modeloEquiposSeleccionados.addElement(seleccionLista);
            modeloEquipos.removeElement(seleccionLista);
        }}else if ("Duo".equals(seleccion)){
        String seleccionLista = (String) jLEquiposDuo.getSelectedValue();
        if(seleccionLista !=null && !modeloEquiposDuo.contains(seleccionLista)){
            modeloEquiposSeleccionadosDuo.addElement(seleccionLista);
            modeloEquiposDuo.removeElement(seleccionLista);            
        }}else if("Individual".equals(seleccion)){
            String seleccionLista = (String) jLJugadores.getSelectedValue();
        if(seleccionLista !=null && !modeloJugadores.contains(seleccionLista)){
            modeloJugadoresSeleccionados.addElement(seleccionLista);
            modeloJugadores.removeElement(seleccionLista);            
        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
String seleccion = (String) jCSeleccionTipo.getSelectedItem();
        
        if("Equipos".equals(seleccion)){
        String seleccionLista = (String) jLEquipos.getSelectedValue();
        if(seleccionLista !=null && !modeloEquipos.contains(seleccionLista)){
            modeloEquiposSeleccionados.removeElement(seleccionLista);
            modeloEquipos.addElement(seleccionLista);
        }}else if ("Duo".equals(seleccion)){
        String seleccionLista = (String) jLEquiposDuo.getSelectedValue();
        if(seleccionLista !=null && !modeloEquiposDuo.contains(seleccionLista)){
            modeloEquiposSeleccionadosDuo.removeElement(seleccionLista);
            modeloEquiposDuo.addElement(seleccionLista);            
        }}else if("Individual".equals(seleccion)){
            String seleccionLista = (String) jLJugadores.getSelectedValue();
        if(seleccionLista !=null && !modeloJugadores.contains(seleccionLista)){
            modeloJugadoresSeleccionados.removeElement(seleccionLista);
            modeloJugadores.addElement(seleccionLista);            
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionTorneos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JComboBox<String> jCSeleccionTipo;
    private javax.swing.JList<String> jLEquipos;
    private javax.swing.JList<String> jLEquipos2;
    private javax.swing.JList<String> jLEquiposDuo;
    private javax.swing.JList<String> jLEquiposSeleccionados;
    private javax.swing.JList<String> jLEquiposSeleccionadosDuo;
    private javax.swing.JList<String> jLJugadores;
    private javax.swing.JList<String> jLJugadoresSeleccionados;
    private javax.swing.JList<String> jLJugadoresSeleccionados1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables



}
