/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClasesInterfacez;

import ClasesBean.Equipo;
import ClasesBean.Jugador;
import ClasesBean.Participante;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;


public class RegistroParaEquipos extends javax.swing.JFrame {
    ArrayList<Participante> jugadores = new ArrayList<Participante>();
    /**
     * Creates new form RegistroParaEquipos
     */
    public RegistroParaEquipos() {
        initComponents();
        cargarComboBox();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCBCantidadIntegrantes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTNEquipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCBJugadores = new javax.swing.JComboBox<>();
        jBAJugador = new javax.swing.JButton();
        jBCrearEquipo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTASeleccionados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registro equipos");

        jCBCantidadIntegrantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Duo", "Squad" }));
        jCBCantidadIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCantidadIntegrantesActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del equipo");

        jTNEquipo.setColumns(5);

        jLabel3.setText("Jugadores");

        jBAJugador.setText("Agregar");
        jBAJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAJugadorActionPerformed(evt);
            }
        });

        jBCrearEquipo.setText("Crear equipo");
        jBCrearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearEquipoActionPerformed(evt);
            }
        });

        jTASeleccionados.setEditable(false);
        jTASeleccionados.setColumns(20);
        jTASeleccionados.setRows(5);
        jScrollPane3.setViewportView(jTASeleccionados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBAJugador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBCrearEquipo)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jCBCantidadIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jTNEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jCBCantidadIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCBJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAJugador)
                    .addComponent(jBCrearEquipo))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBCantidadIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCantidadIntegrantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCantidadIntegrantesActionPerformed

    private void jBAJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAJugadorActionPerformed
        jTASeleccionados.append((String)jCBJugadores.getSelectedItem() + "\n");
        jugadores.add( encontrarJugador((String)jCBJugadores.getSelectedItem()));

    }//GEN-LAST:event_jBAJugadorActionPerformed

    private void jBCrearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearEquipoActionPerformed
        if(jCBCantidadIntegrantes.getSelectedItem().equals("Duo")&& jugadores.size()==2){            
        escribirDuos(new Equipo(jTNEquipo.getText(), (String) jCBCantidadIntegrantes.getSelectedItem(), jugadores));            
        }else if(jCBCantidadIntegrantes.getSelectedItem().equals("Squad")&& jugadores.size()==4){
        escribirSquads(new Equipo(jTNEquipo.getText(), (String) jCBCantidadIntegrantes.getSelectedItem(), jugadores));
        }
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_jBCrearEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroParaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroParaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroParaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroParaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroParaEquipos().setVisible(true);
            }
        });
    }
    
    
    
//Metodos
     public void cargarComboBox(){
       
    String linea;
        try(BufferedReader br = new BufferedReader(new FileReader("archivos/jugadores.txt"))){
            while((linea=br.readLine()) !=null){
                String[] partes = linea.split(";");
                jCBJugadores.addItem(partes[3]);
            }
        }catch(IOException e){
            e.printStackTrace();
        }
      
     }  

     public static void escribirDuos(Equipo equipo) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("archivos/duos.txt", true))) {
            List<Participante> jugadores = equipo.retornarJugadores();
            List<String> nicknames = new ArrayList<>();
            for (Participante p : jugadores) {
                nicknames.add(p.getNickname());
            }
            String jugadoresStr = String.join(",", nicknames);

            bw.write(equipo.getNombre() + ";" + equipo.getTipo() + ";" + jugadoresStr);
            bw.newLine();
        } catch (IOException ex) {
            System.out.println("Error al escribir duo: " + ex.getMessage());
        }
    }

    public static void escribirSquads(Equipo equipo) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("archivos/equipos.txt", true))) {
            List<Participante> jugadores = equipo.retornarJugadores();
            List<String> nicknames = new ArrayList<>();
            for (Participante p : jugadores) {
                nicknames.add(p.getNickname());
            }
            String jugadoresStr = String.join(",", nicknames);

            bw.write(equipo.getNombre() + ";" + equipo.getTipo() + ";" + jugadoresStr);
            bw.newLine();
        } catch (IOException ex) {
            System.out.println("Error al escribir equipo: " + ex.getMessage());
        }
    }

    public static Participante encontrarJugador(String nickname) {
        File archivo = new File("archivos/jugadores.txt");
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(";");
                if (partes.length >= 7 && partes[3].equalsIgnoreCase(nickname)) {
                    String cedula = partes[0];
                    int edad = Integer.parseInt(partes[1]);
                    String nombre = partes[2];
                    String nick = partes[3];
                    String pais = partes[4];
                    int ranking = Integer.parseInt(partes[5]);
                    int victorias = Integer.parseInt(partes[6]);

                    return new Participante(cedula, edad, nombre, nick, pais, ranking, victorias);
                }
            }
        } catch (IOException ex) {
            System.out.println("Error al encontrar jugador: " + ex.getMessage());
        }
        return null;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAJugador;
    private javax.swing.JButton jBCrearEquipo;
    private javax.swing.JComboBox<String> jCBCantidadIntegrantes;
    private javax.swing.JComboBox<String> jCBJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTASeleccionados;
    private javax.swing.JTextField jTNEquipo;
    // End of variables declaration//GEN-END:variables
}
